import { Router } from "express";
import { z } from "zod";
import { prisma } from "../db/prisma.js";
import { requireAuth } from "../middleware/auth.js";
import { hashPassword, validatePassword, verifyPassword } from "../security/password.js";
const router=Router();router.use(requireAuth);const safe={id:true,name:true,email:true,role:true,active:true,createdAt:true,updatedAt:true} as const;const fail=(r:any,s:number,e:string)=>r.status(s).json({error:e});
router.get("/",async(q,r,n)=>{try{const u=await prisma.user.findUnique({where:{id:q.authUser!.id},select:safe});u?r.json({user:u}):fail(r,401,"Authentication required.")}catch(e){n(e)}});
router.patch("/",async(q,r,n)=>{const p=z.object({name:z.string().trim().min(1).max(150).optional(),email:z.string().trim().toLowerCase().email().max(320).optional()}).strict().safeParse(q.body);if(!p.success||!Object.keys(p.data).length)return fail(r,400,"Invalid request data.");try{const u=await prisma.$transaction(async t=>{const old=await t.user.findUnique({where:{id:q.authUser!.id}});if(!old)throw Error("AUTH");const changes:any={};for(const k of ["name","email"] as const)if(p.data[k]!==undefined&&p.data[k]!==old[k])changes[k]={from:old[k],to:p.data[k]};const user=await t.user.update({where:{id:old.id},data:p.data,select:safe});if(Object.keys(changes).length)await t.userAuditLog.create({data:{actorUserId:old.id,targetUserId:old.id,action:"USER_UPDATED",metadata:{changes}}});return user});r.json({user:u})}catch(e:any){if(e.code==="P2002")return fail(r,409,"El correo electrónico ya está registrado.");n(e)}});
router.post("/change-password",async(q,r,n)=>{const p=z.object({currentPassword:z.string(),newPassword:z.string(),confirmPassword:z.string()}).strict().safeParse(q.body);if(!p.success)return fail(r,400,"Invalid request data.");if(p.data.newPassword!==p.data.confirmPassword)return fail(r,400,"Passwords do not match.");try{const u=await prisma.user.findUnique({where:{id:q.authUser!.id}});if(!u||!await verifyPassword(u.passwordHash,p.data.currentPassword))return fail(r,400,"La contraseña actual es incorrecta.");const m=validatePassword(p.data.newPassword,u.email);if(m)return fail(r,400,m);await prisma.$transaction([prisma.user.update({where:{id:u.id},data:{passwordHash:await hashPassword(p.data.newPassword)}}),prisma.userAuditLog.create({data:{actorUserId:u.id,targetUserId:u.id,action:"PASSWORD_CHANGED_SELF"}})]);r.status(204).send()}catch(e){n(e)}});export {router as accountRouter};
