import { useEffect, useState } from "react";
import { productsApi, productVariantsApi, type ApiProduct, type ApiProductVariant } from "../lib/api";
import type { Screen } from "../types/navigation";
import { Badge } from "../components/ui/Badge";
import { Btn } from "../components/ui/Button";
import { Icon } from "../components/ui/Icon";
import { Icons } from "../components/ui/icons";
import { Input } from "../components/ui/Input";
import { Modal } from "../components/ui/Modal";
import { TopBar } from "../components/layout/TopBar";
import { ProductImageGallery } from "../components/product/ProductImageGallery";
import { LabelArtwork } from "../components/barcode/LabelArtwork";
import { ProductVariantLabel } from "../components/barcode/ProductVariantLabel";
import { apiMessage } from "../utils/api-error";
import { getStatusColor, getStatusLabel, productVisualStatus, variantVisualStatus } from "../utils/inventory";

export function RealProductDetailScreen({ productId, onNavigate, onUnauthorized }: { productId: string; onNavigate: (screen: Screen, data?: unknown) => void; onUnauthorized: () => void }) {
  const [product, setProduct] = useState<ApiProduct | null>(null); const [error, setError] = useState(""); const [variantModal, setVariantModal] = useState(false); const [editing, setEditing] = useState<ApiProductVariant | null>(null); const [variant, setVariant] = useState<ProductVariantInput>({ size: null, color: null, minimumStock: 0 }); const [variantActive, setVariantActive] = useState(true); const [labelVariant, setLabelVariant] = useState<ApiProductVariant | null>(null); const [labelCopies, setLabelCopies] = useState("1"); const [labelError, setLabelError] = useState("");
  const load = async () => { try { const result = await productsApi.get(productId); setProduct(result.product); } catch (requestError) { setError(apiMessage(requestError, "No se pudo cargar el producto.", onUnauthorized)); } };
  useEffect(() => { void load(); }, [productId]);
  const openNew = () => { setEditing(null); setVariant({ size: null, color: null, minimumStock: 0 }); setVariantActive(true); setVariantModal(true); };
  const openEdit = (item: ApiProductVariant) => { setEditing(item); setVariant({ size: item.size, color: item.color, minimumStock: item.minimumStock }); setVariantActive(item.active); setVariantModal(true); };
  const openLabel = (item: ApiProductVariant) => { setLabelVariant(item); setLabelCopies("1"); setLabelError(""); };
  const printableCopies = Number(labelCopies);
  const printLabels = () => {
    if (!Number.isInteger(printableCopies) || printableCopies < 1 || printableCopies > 100) return setLabelError("Ingresa entre 1 y 100 etiquetas.");
    setLabelError("");
    window.print();
  };
  const saveVariant = async () => { if (!product) return; setError(""); try { if (editing) await productsApi.updateVariant(product.id, editing.id, { minimumStock: variant.minimumStock, active: variantActive }); else await productsApi.addVariant(product.id, { size: product.category.usesSizes ? variant.size?.trim() || null : null, color: variant.color?.trim() || null, minimumStock: variant.minimumStock }); setVariantModal(false); await load(); } catch (requestError) { setError(apiMessage(requestError, "No se pudo guardar la variante.", onUnauthorized)); } };
  if (!product) return <div className="flex-1 flex items-center justify-center text-sm text-[#6B6560]">{error || "Cargando producto..."}</div>;
  const status = productVisualStatus(product);
  return <div className="flex-1 flex flex-col overflow-hidden"><TopBar title="Detalle del producto" subtitle={product.name} actions={<div className="flex gap-2"><Btn variant="ghost" size="sm" onClick={() => onNavigate("inventory")}><Icon path={Icons.back} size={14} />Volver</Btn><Btn variant="secondary" size="sm" onClick={openNew}><Icon path={Icons.plus} size={14} />Agregar variante</Btn><Btn variant="primary" size="sm" onClick={() => onNavigate("product-edit", product)}><Icon path={Icons.edit} size={14} />Editar</Btn></div>} />
    <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="max-w-3xl mx-auto space-y-5">{error && <div className="bg-[#FFEBEE] border border-[#C62828] text-[#C62828] rounded px-4 py-3 text-sm">{error}</div>}<div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><div className="space-y-3"><ProductImageGallery product={product} onUnauthorized={onUnauthorized} /><div className="flex justify-center"><Badge label={getStatusLabel(status)} color={getStatusColor(status)} /></div></div><div className="col-span-1 lg:col-span-2 bg-white rounded-lg border border-[#E2DDD7] p-5 shadow-sm space-y-4"><div><h2 className="text-xl font-semibold text-[#1A1A1A]" style={{ fontFamily: "var(--font-display)" }}>{product.name}</h2><p className="font-mono text-xs text-[#6B6560] mt-1">{product.skuBase}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div><p className="text-[10px] uppercase text-[#6B6560]">Categoría</p><p>{product.category.name}</p></div><div><p className="text-[10px] uppercase text-[#6B6560]">Programa</p><p>{product.program.name}</p></div><div><p className="text-[10px] uppercase text-[#6B6560]">Creadora</p><p>{product.creatorName}</p></div><div><p className="text-[10px] uppercase text-[#6B6560]">Estado</p><p>{product.active ? "Activo" : "Inactivo"}</p></div></div><div><p className="text-[10px] uppercase text-[#6B6560]">Descripción</p><p className="text-sm">{product.description}</p></div>{product.history && <div><p className="text-[10px] uppercase text-[#6B6560]">Historia</p><p className="text-sm">{product.history}</p></div>}</div></div>
      <div className="bg-white rounded-lg border border-[#E2DDD7] shadow-sm overflow-x-auto"><div className="px-5 py-3.5 border-b border-[#E2DDD7]"><h3 className="text-sm font-semibold">Variantes</h3></div><table className="min-w-[42rem] w-full text-sm"><thead className="bg-[#F5F3F0]"><tr>{["SKU", "Talla", "Color", "Stock", "Mínimo", "Estado", "Acciones"].map((header) => <th key={header} className="text-left px-5 py-3 text-xs font-medium text-[#6B6560] uppercase border-b border-[#E2DDD7]">{header}</th>)}</tr></thead><tbody className="divide-y divide-[#E2DDD7]">{product.variants.map((item) => { const itemStatus = variantVisualStatus(item); return <tr key={item.id}><td className="px-5 py-3 font-mono text-xs">{item.sku}</td><td className="px-5 py-3">{item.size || "—"}</td><td className="px-5 py-3">{item.color || "—"}</td><td className="px-5 py-3 font-semibold">{item.stock}</td><td className="px-5 py-3">{item.minimumStock}</td><td className="px-5 py-3"><Badge label={getStatusLabel(itemStatus)} color={getStatusColor(itemStatus)} /></td><td className="px-5 py-3"><div className="flex items-center gap-1"><Btn variant="ghost" size="sm" onClick={() => openEdit(item)}><Icon path={Icons.edit} size={13} /></Btn><Btn variant="ghost" size="sm" onClick={() => openLabel(item)}>Etiqueta</Btn></div></td></tr>; })}</tbody></table></div></div></div>
    {labelVariant && <Modal title="Vista previa de etiqueta" onClose={() => setLabelVariant(null)} width="max-w-3xl"><div className="space-y-4"><div className="label-preview-stage"><LabelArtwork product={product} variant={labelVariant} preview /></div><p className="text-xs text-[#6B6560]">Stock actual: <strong className="text-[#1A1A1A]">{labelVariant.stock}</strong></p><Input label="Cantidad de etiquetas" type="number" value={labelCopies} onChange={setLabelCopies} required />{labelError && <p className="text-xs text-[#C62828]">{labelError}</p>}<div className="flex justify-end gap-2"><Btn variant="secondary" onClick={() => setLabelVariant(null)}>Cancelar</Btn><Btn variant="primary" onClick={printLabels}>Imprimir etiquetas</Btn></div><ProductVariantLabel product={product} variant={labelVariant} copies={Number.isInteger(printableCopies) && printableCopies >= 1 && printableCopies <= 100 ? printableCopies : 1} /></div></Modal>}
    {variantModal && <Modal title={editing ? "Editar variante" : "Agregar variante"} onClose={() => setVariantModal(false)}><div className="space-y-4">{product.category.usesSizes && <Input label="Talla" value={variant.size || ""} onChange={(size) => setVariant({ ...variant, size })} readOnly={!!editing} required />}<Input label="Color" value={variant.color || ""} onChange={(color) => setVariant({ ...variant, color })} readOnly={!!editing} /><Input label="Stock mínimo" type="number" value={String(variant.minimumStock)} onChange={(value) => setVariant({ ...variant, minimumStock: Number(value) })} />{editing && <><Input label="SKU" value={editing.sku} readOnly /><Input label="Stock" value={String(editing.stock)} readOnly /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={variantActive} onChange={(event) => setVariantActive(event.target.checked)} className="accent-[#2D6A6A]" />Variante activa</label></>}<div className="flex justify-end gap-2"><Btn variant="secondary" onClick={() => setVariantModal(false)}>Cancelar</Btn><Btn variant="primary" onClick={() => void saveVariant()}>Guardar</Btn></div></div></Modal>}
  </div>;
}

